# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-14 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170814_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='author',
            new_name='authors',
        ),
    ]
